
//! 123
//! Error
//! EXCEPTION! Test

import lib.libcore

try println(str(123)) {
    _ => println("Error")
}

fn test() {
    raise "error"
}

try test() {
    _ => println("Error")
}

try {
    raise "Test"
    ()
} catch {
    e => println("EXCEPTION! " + e)
}

